<?php

$custom_style .= '

    body,
    #respond #author,
    #respond #email,
    #respond #url,
    #respond #comment,
    .gbtr_light_footer_no_widgets,
    .gbtr_widget_footer_from_the_blog .gbtr_widget_item_title,
    .widget input[type=text],
    .widget input[type=password],
    .widget input[type=search],
    .widget select,
    .gbtr_tools_search_inputtext,
    .gbtr_second_menu,
    .gbtr_little_shopping_bag .overview,
    .gbtr_featured_section_title,
    .product_item p,
    .woocommerce-product-details__short-description,
    div.product form.cart .variations .value select,
    #content div.product form.cart .variations .value select,
    div.product .woocommerce_tabs .panel,
    #content div.product .woocommerce_tabs .panel,
    div.product .woocommerce-tabs .panel,
    #content div.product .woocommerce-tabs .panel,
    .coupon .input-text,
    .cart_totals .shipping td,
    .shipping_calculator h3,
    .checkout .input-text,
    table.shop_table tfoot .shipping td,
    .gbtr_checkout_login .input-text,
    table.my_account orders .order-number a,
    .myaccount_user,
    .order-info,
    .select2-results,
    .myaccount_user span,
    .track_order p:first-child,
    .order-info span,
    .select2-selection__rendered,
    .sf-menu li li a,
    .shortcode_banner_simple_inside h3,
    .shortcode_banner_simple_inside h3 strong,
    .mc_var_label,
    form .form-row .input-text,
    form .form-row textarea,
    form .form-row select,
    #icl_lang_sel_widget a,
    .group_table .label a,
    .gbtr_footer_widget_copyrights,
    .wpcf7 input,
    .wpcf7 textarea,
    #ship-to-different-address label,
    #ship-to-different-address .checkbox,
    .wpcf7 select,
    .cart_list_product_title,
    .wpb_tabs .ui-widget,
    .minicart_product,
    table.my_account_orders td.order-total,
    .select2-search input,
    #respond .comment-form-cookies-consent label,
    form .comment-form-cookies-consent label,
    .variation dt,
    .variation dd p,
    .woocommerce table.my_account_orders.shop_table .amount,
    #yith-wcwl-form .wishlist_table .product-name h3,
    div.product .group_table tr td.woocommerce-grouped-product-list-item__label a
	{
		font-family: ' . TheRetailer_Fonts::get_main_font() . ';
	}

    h1, h2, h3, h4, h5, h6,
    .tr_upper_link,
    .shortcode_banner_simple_inside h4,
    .shortcode_banner_simple_height h4,
    .shortcode_banner_simple_bullet,
    .shortcode_banner_simple_height_bullet,
    .main-navigation .mega-menu > ul > li > a,
    .cbutton,
    .widget h4.widget-title,
    .widget input[type=submit],
    .widget.widget_shopping_cart .total,
    .widget.widget_shopping_cart .total strong,
    ul.product_list_widget span.amount,
    .gbtr_tools_info,
    .gbtr_little_shopping_bag .title,
    .product_item h3,
    .product_item .price,
    a.button,
    button.button,
    input.button,
    #respond input#submit,
    #content input.button,
    div.product .product_brand,
    div.product .summary span.price,
    div.product .summary p.price,
    #content div.product .summary span.price,
    #content div.product .summary p.price,
    .quantity input.qty,
    #content .quantity input.qty,
    div.product form.cart .variations .label,
    #content div.product form.cart .variations .label,
    .gbtr_product_share ul li a,
    div.product .woocommerce-tabs .tabs-list ul.tabs li a,
    table.shop_table th,
    table.shop_table .product-name .category,
    table.shop_table td.product-subtotal,
    .coupon .button-coupon,
    .cart_totals th,
    .cart_totals td,
    form .form-row label,
    table.shop_table td.product-quantity,
    table.shop_table td.product-name .product_brand,
    table.shop_table td.product-total,
    table.shop_table tfoot th,
    table.shop_table tfoot td,
    .gbtr_checkout_method_content .title,
    table.my_account_orders td.order-total,
    .addresses .title h3,
    .sf-menu a,span.onsale,
    .product h3,
    #respond label,
    form label,
    form input[type=submit],
    .section_title,
    .gbtr_little_shopping_bag_wrapper_mobiles span,
    .grtr_product_header_mobiles .price,
    .woocommerce-message,
    .woocommerce-error,
    .woocommerce-info,p.product,
    .from_the_blog_date,
    .gbtr_dark_footer_wrapper .widget_nav_menu ul li,
    .widget.the_retailer_recent_posts .post_date,
    .featured_products_slider .products_slider_category,
    .featured_products_slider .products_slider_price,
    .page_archive_subtitle,
    .mc_var_label,
    .theretailer_style_intro,
    .wpmega-link-title,
    .group_table .price,
    .shopping_bag_centered_style > span,
    .customer_details dt,
    #lang_sel_footer,
    .out_of_stock_badge_single,
    .out_of_stock_badge_loop,
    .portfolio_categories li,
    #load-more-portfolio-items,
    .portfolio_details_item_cat,
    .yith-wcwl-add-button,
    table.shop_table .amount,
    .woocommerce table.shop_table .amount,
    .yith-wcwl-share h4,
    .wishlist-out-of-stock,
    .wishlist-in-stock,
    .orderby,
    .select2-container,
    .big-select,
    select.big-select,
    .woocommerce-result-count,
    .messagebox_text,
    .vc_progress_bar,
    .wpb_heading.wpb_pie_chart_heading,
    .shortcode_icon_box .icon_box_read_more,
    .vc_btn,
    ul.cart_list .empty,
    .gbtr_minicart_wrapper .woocommerce-mini-cart__empty-message,
    .tagcloud a,
    .trigger-share-list,
    .box-share-link,
    .woocommerce table.shop_table_responsive tr td:before,
    .woocommerce-page table.shop_table_responsive tr td:before,
    table.my_account_orders td.order-total .amount,
    .shipping-calculator-button,
    .vc_btn3,
    .woocommerce-cart .woocommerce .cart-collaterals h2,
    li.woocommerce-MyAccount-navigation-link a,
    p.has-drop-cap:first-letter,
    .comment-author,
    .comments-area .comment-list .reply,
    .woocommerce-Reviews #review_form_wrapper .comment-reply-title,
    #nav-below .nav-previous-single a,
    #nav-below .nav-next-single a,
    .more-link,
    div.product div.product_meta,
    .woocommerce div.product p.stock,
    .gbtr_items_sliders_title,
    .product_title,
    .gbtr_header_wrapper .site-title a,
    .gbtr_header_wrapper .mobile-site-title a,
    .mobile-main-navigation ul.sf-menu > li > .sub-menu > li.menu-item-has-children > a,
    .js-offcanvas.c-offcanvas--top .search-text,
    .woocommerce div.product .product_main_infos .gbtr_product_details_right_col form.cart .variations select,
    a.reset_variations,
    .gbtr_header_wrapper .shopping_bag_mobile_style .gb_cart_contents_count,
    .shop_offcanvas_button span,
    form.login.woocommerce-form-login .lost_password,
    #customer_details .woocommerce-billing-fields h3,
    #customer_details .woocommerce-shipping-fields h3 span,
    .woocommerce-breadcrumb,
    .wc-block-grid__product-add-to-cart a.wp-block-button__link,
    .wc-block-grid__product-onsale,
    .wc-block-grid__product-price,
    .gbt_18_default_slider .gbt_18_content .gbt_18_content_wrapper .gbt_18_slide_link a,
    .gbt_18_expanding_grid .gbt_18_product_price,
    .gbt_18_distorsion_lookbook .gbt_18_product_price,
    .woocommerce a.button,
    .woocommerce button.button,
    .woocommerce button.button.alt,
    .woocommerce input.button,
    .woocommerce #respond input#submit,
    .woocommerce #content input.button,
    .woocommerce-widget-layered-nav-dropdown__submit,
    button.wc-stripe-checkout-button,
    .button_create_account_continue,
    .button_billing_address_continue,
    .addresses a,
    .button_shipping_address_continue,
    .button_order_review_continue,
    #place_order,
    .single_add_to_cart_button,
    .more-link:hover,
    .woocommerce-cart .wc-proceed-to-checkout a.checkout-button:hover,
    .woocommerce .woocommerce-table--order-downloads a.button.alt,
    .group_table span.woocommerce-Price-amount.amount,
    .wc-block-order-select .wc-block-order-select__label,
    .wc-block-order-select .wc-block-order-select__select,
    .wp-block-latest-posts li > a, .wp-block-latest-posts .wp-block-latest-posts__post-excerpt > a,
    .wp-block-latest-posts__post-date,
    .wcva_filter_textblock, .wcva_single_textblock, .wcvashopswatchlabel.wcva_shop_textblock
	{
		font-family: ' . TheRetailer_Fonts::get_secondary_font() . ';
	}
';

?>
